### ISSUE TITLE
增加自动复制验证码功能

### ISSUE THREAD

**Issue by QM123** [Adpro-Team/GKD_THS_List#11]
能不能弄一个自动复制验证码功能？
实现：任何界面，当收到验证码短信时，自动点击复制验证码。
设备：荣耀V30PRO   系统：鸿蒙4.0
快照：https://i.gkd.li/import/14368820

**Comment by QM123** [comment]
> 你好，无法适配。

为什么？

**Comment by adproqwq** [comment]
> > 你好，无法适配。
> 
> 为什么？

不支持鸿蒙系统，另外，该项目不用于规则适配请求。
