### ISSUE TITLE
如果导入相似功能过多的规则会怎么样？

### ISSUE THREAD

**Issue by wg961** [Adpro-Team/GKD_THS_List#16]
萌新难以对比过多的规则之间的差异，又担心会有所遗漏，所以将所有的规则都导入并打开

**Comment by wg961** [comment]
额，看了一下触发记录，好像是第一个订阅有的规则会直接用，然后第一个没有的才会按顺序往下找到有的

**Comment by adproqwq** [comment]
> 好像是第一个订阅有的规则会直接用，然后第一个没有的才会按顺序往下找到有的

大部分情况是这样的。但是在部分情况下，多个规则可能会冲突。
