### ISSUE TITLE
gitmirror源下载订阅文件失败

### ISSUE THREAD

**Issue by FeyWAnGG** [Adpro-Team/GKD_THS_List#19]
复制了规则的链接，在gkd中粘贴订阅链接，提示下载订阅文件失败，几个链接都这样。以前成功导入的链接还在的，可以正常更新。

**Comment by adproqwq** [comment]
请暂时暂停使用gitmirror源导入，具体恢复时间等待通知。
在此期间，请换用其它源。

**Comment by AIsouler** [comment]
推荐npmmirror源
