### ISSUE TITLE
如何在李跳跳中添加gdk订阅

### ISSUE THREAD

**Issue by lxccc812** [Adpro-Team/GKD_THS_List#27]
如题，我只看到了txt式的订阅，但是网上说效果不如gdk，但是我找了一圈也没看到如何使用gkd订阅，教教🥹🥴

**Comment by Anivie** [comment]
直接下载[gkd](https://github.com/gkd-kit/gkd)并选一个你喜欢的规则导入进去就行了

**Comment by lxccc812** [comment]
已成功导入，谢谢
